language: node_js

services:
  - docker

install: true

before_script:
  - bash build_deploy.sh build

script:
  - docker run "$DOCKER_IMAGE" npm run check4updates

deploy:
  provider: script
  script: bash build_deploy.sh deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE != cron